---
title: "Crime Statistics Victoria 2016-2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
---
```{r}
library(flexdashboard)
library(readr)
library(dplyr)
library(readxl)
library(tidyr)
library(knitr)
library(ggiraph)
library(plotly)
library(ggplot2)
library(gganimate)
#Crime Incident file
crime<-read_xlsx("main excel.xlsx",sheet = "Sheet2",skip = 3)
#Affected Family Member file
famcrime<-read_xlsx("famcrime.xlsx",sheet = "Sheet4")
colorscheme <- c('#4AC6B7', '#1972A4', '#965F8A', '#FF7070', '#C61951')
#Harm flag file
harm<-read_xlsx("harm.xlsx",sheet="Sheet1",skip = 3)
harm<-harm[-11,-5]
harm1<-gather(harm,'High Harm','Low Harm','Medium Harm',key="Harm Caused Flag",value="Total Count")
harm2<-filter(harm1,Year>=2016)
harm2$`Harm Caused Flag`<-factor(harm2$`Harm Caused Flag`,levels = c("High Harm","Medium Harm","Low Harm"))
#charges status file
charges<-read_xlsx("main excel.xlsx",sheet = "Sheet4",skip = 3)
charges1<-charges[-4,-12]
charges2<-gather(charges1,'2011','2012','2013','2014','2015','2016','2017','2018','2019','2020',key="Year",value="Number")
charges3<-filter(charges2,charges2$Year>=2016)
names(charges3)[names(charges3) == "Row Labels"] <- "Charge Status"
```

Column 
-------------------------------------

### **Criminal Incidents - Victoria : 2016 - 2020**
    
```{r,fig.align='left', fig.width=7,fig.height=17}
crime1<-crime[-c(6,7),-12]
crime1<-gather(crime1,'2011','2012','2013','2014','2015','2016','2017','2018','2019','2020',key="Year",value="Number")
names(crime1)[names(crime1) == "Row Labels"] <- "Type"
names(crime1)[names(crime1) == "Number"] <- "Total Count"
crime2<-filter(crime1,Year >=2016)
viccrime<-ggplot(crime2, aes(`Total Count`,Type))+
  geom_bar(aes(fill=Year),stat= "identity",position = "dodge",width = 0.9)+
 theme_bw()+
  scale_fill_manual(values=c('#c7e9b4', '#7fcdbb', '#41b6c4', '#2c7fb8', '#253494'))+
  xlab("Total Count (in Thousands)") +
  ylab("Offence Division")
theme<-theme( plot.title = element_text(face="bold",size = 15),
              axis.text = element_text(face="bold",size = 10),
              axis.title = element_text(face = "bold",size=10))
a<-viccrime +theme+
  scale_x_continuous(
    breaks = c(0,25000,50000,75000,100000,125000,150000,175000,200000,225000,250000,275000),
    labels = c("0","25","50","75","100","125","150","175","200","225","250","275"))
ggplotly(a,tooltip=c("Year","Total Count"))
```

### **Harm Caused Intensity - 2016-2020**

```{r, fig.height=17}
h<-ggplot(harm2, aes(`Year`,`Total Count`))+
  geom_bar(aes(fill=`Harm Caused Flag`),stat= "identity",position = "stack",width = 0.4)+
  theme_bw()+
  scale_fill_manual(values=c('#de2d26', '#fc9272', '#fee0d2'))+
  xlab("Year") +
  ylab("Total Count")
theme<-theme( plot.title = element_text(face="bold",size = 15),
              axis.text = element_text(face="bold",size = 10),
              axis.title = element_text(face = "bold",size=10))
h1<-h +theme+
  scale_y_continuous(
    breaks = c(0,25000,50000,75000,100000,125000,150000,175000,200000,225000,250000),
    labels = c("0","25","50","75","100","125","150","175","200","225","250"))
ggplotly(h1,tooltip=c("Year","Harm Caused Flag", "Total Count"))

```   

### Reference

Victoria Crime Data | Download data | Crime Statistics Agency Victoria. (2020, September 18). Crime Statistics Agency. https://www.crimestatistics.vic.gov.au/crime-statistics/latest-victorian-crime-data/download-data

Column {.tabset .tabset-fade}
-------------------------------------
   
### **Affected Family Member-Gender & Age Wise 2016-2020**

```{r}
afm <- plot_ly(
  famcrime, x = famcrime$`AFM Sex`, y = famcrime$`AFM Counter`,
  frame=famcrime$Year,
  color = famcrime$`AFM Age Group`, type = "scatter",
  mode="markers", size= famcrime$`AFM Counter`, colors= colorscheme,
  marker = list(symbol = 'circle', sizemode = 'diameter',
                line = list(width = 1.5, color = 'grey'), opacity=0.5))%>%
  layout(
        xaxis = list(title ="Gender",
                 zerolinewidth = 1,
                 gridwidth = 1.5),
         yaxis = list(title = "Total Count",
                 range=c(0,19000),
                 gridwith = 1.5),
        paper_bgcolor = '#FFFFFF',
        plot_bgcolor = '#FFFFFF')
afm1<- animation_opts(afm,frame= 2500) %>%
animation_slider(currentvalue = list(prefix = "YEAR ", font = list(color="black")))

afm1
```   

### **Criminal Incident Charge Status-2016-2020**
    
```{r}
cs<-ggplot(charges3, aes(x=`Charge Status`, y=`Number`, group=Year)) +
  geom_line(aes(color=`Year`))+
  geom_point(aes(color=`Year`))
cg<-cs+scale_color_manual(values=c("#1b9e77", "#d95f02", "#7570b3","#e7298a","#66a61e"))
ggplotly(cg)

```